### ISSUE TITLE
Nuget Package not up date 

### ISSUE THREAD

**Issue by phlegma** [Scooletz/NGitLab#12]
just discovered that the newest version of the repository is not deployed to nuget. 
Any change to start the deploy or any hint how to do this. 
![ngitlabversion](https://cloud.githubusercontent.com/assets/358332/5722770/4f185974-9b3f-11e4-8fe1-9b672d91b442.PNG)

**Comment by Scooletz** [comment]
I need to provide some PSake script for build, but yes, I can do this by the end of a week. This project doesn't have a build server behind so it requires manual builds but with some scripting, it can be easily done.

**Comment by phlegma** [comment]
thanx a lot.

**Comment by Scooletz** [comment]
I've just pushed the latest build. It contains gzip fix and more.
There's one missing: https://github.com/Scooletz/NGitLab/pull/9 but it would take me a while to make it ergable. If you could make it an easy merge and review it, I'd be more than happy to accept this.
